# .github/workflows/build.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Ensure no DMG is mounted
        for vol in "/Volumes/7Zip GUI"*; do
          if [ -d "$vol" ]; then
            hdiutil detach "$vol" -force || true
          fi
        done
        npm run build
        
    - name: Prepare Release Files
      run: |
        mkdir release
        cp dist/*.dmg release/ || true
        cp dist/*.zip release/ || true
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.dmg
          release/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
